steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/macro-nuance-416801/my-streamlit-app', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/macro-nuance-416801/my-streamlit-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'my-streamlit-app', '--image', 'gcr.io/macro-nuance-416801/my-streamlit-app', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

images:
- gcr.io/macro-nuance-416801/my-streamlit-app
